# blastradius is free and MIT-licensed. If it saves your team time, sponsoring keeps it
# maintained. Pro licenses (html/sarif/baseline) are the other way to support it — see
# the README.
github: [earbona23]
patreon: EduardArbona
