/**
 * Self-contained HTML report (a Pro output). One file, no external assets, light/dark,
 * printable. Renders either a criticality survey or a change blast-radius, whichever the
 * caller passes. Every path and label comes from the codebase and is escaped.
 *
 * @module report/html
 */

/**
 * @param {Object} data
 * @param {'criticality'|'impact'} data.kind
 * @param {string} data.project
 * @param {string} data.generatedAt
 * @param {string} data.toolVersion
 * @param {Object} data.payload   Criticality entries or an impact report.
 * @param {Object} data.stats
 * @returns {string}
 */
export function renderHtml(data) {
  const body = data.kind === 'impact' ? impactBody(data) : criticalityBody(data);
  return [
    '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    `<title>blastradius — ${esc(data.project)}</title>`,
    `<style>${STYLE}</style></head><body><main class="wrap">`,
    `<header><p class="eyebrow">blastradius · ${data.kind === 'impact' ? 'change blast radius' : 'criticality survey'}</p>`,
    `<h1>${esc(data.project)}</h1>`,
    `<p class="sub">${esc(data.generatedAt)} · ${data.stats.files} files · ${data.stats.edges} edges · blastradius ${esc(data.toolVersion)}</p></header>`,
    body,
    '<footer>Generated by <strong>blastradius</strong>. Criticality is graph position; risk folds in test coverage. A graph-based analysis, not a runtime profile.</footer>',
    '</main></body></html>',
  ].join('\n');
}

function criticalityBody(data) {
  const entries = data.payload;
  const rows = entries
    .map((e) => {
      const cls = e.score >= 70 ? 'hi' : e.score >= 40 ? 'mid' : 'lo';
      return `<tr><td class="score ${cls}">${e.score}</td><td class="bar"><span class="${cls}" style="width:${e.score}%"></span></td>` +
        `<td class="file">${esc(e.file)}</td><td class="num">${e.dependents}</td>` +
        `<td>${e.tested ? '<span class="ok">covered</span>' : '<span class="gap">no test</span>'}</td></tr>`;
    })
    .join('');
  return `<section><table class="grid"><thead><tr><th>Score</th><th></th><th>File</th><th class="num">Dependents</th><th>Coverage</th></tr></thead><tbody>${rows}</tbody></table></section>`;
}

function impactBody(data) {
  const r = data.payload;
  const vc = { low: 'lo', moderate: 'mid', high: 'mid', critical: 'hi' }[r.verdict] ?? 'lo';
  const changed = r.changed
    .map((f) => `<li>${esc(f)}${r.untestedTouched.includes(f) ? ' <span class="gap">untested</span>' : ''}</li>`)
    .join('');
  const impacted = r.impacted
    .map((i) => `<tr><td class="num">+${i.distance}</td><td class="score ${i.criticality >= 70 ? 'hi' : i.criticality >= 40 ? 'mid' : 'lo'}">${i.criticality}</td>` +
      `<td class="file">${esc(i.file)}</td><td>${i.tested ? '<span class="ok">covered</span>' : '<span class="gap">no test</span>'}</td></tr>`)
    .join('');
  return [
    `<section class="verdict ${vc}"><div class="risk">${r.risk}<span>/100</span></div>`,
    `<div><div class="vlabel">${esc(r.verdict)} risk</div>`,
    `<div class="factors">blast radius ${r.factors.blastRadius} · peak criticality ${r.factors.peakCriticality} · exposure ${r.factors.exposure} · test gap ${r.factors.testGapPercent}%</div></div></section>`,
    `<section><h2>Changed (${r.changed.length})</h2><ul class="changed">${changed || '<li>—</li>'}</ul></section>`,
    `<section><h2>Impacted (${r.impacted.length})</h2>`,
    r.impacted.length
      ? `<table class="grid"><thead><tr><th class="num">Dist</th><th>Crit</th><th>File</th><th>Coverage</th></tr></thead><tbody>${impacted}</tbody></table></section>`
      : '<p class="ok">Nothing else imports the changed files — the radius is contained.</p></section>',
  ].join('\n');
}

const STYLE = `
:root{color-scheme:light dark;--bg:#eef1f5;--surface:#fff;--surface2:#f6f8fa;--ink:#12161c;--muted:#5a6675;--line:#e0e5eb;--accent:#5b3fd6;--hi:#b02a1f;--mid:#9a6a00;--lo:#1f7a44;--radius:12px}
@media(prefers-color-scheme:dark){:root{--bg:#0c1016;--surface:#141a22;--surface2:#1a212b;--ink:#e6edf5;--muted:#94a2b4;--line:#232c38;--accent:#9d86ff;--hi:#ff6a5c;--mid:#e5b93f;--lo:#46c07a}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.6 ui-sans-serif,-apple-system,"Segoe UI",Roboto,sans-serif}
.wrap{max-width:1000px;margin:0 auto;padding:0 24px 64px}
header{padding:34px 0 8px}.eyebrow{margin:0;font-size:12px;letter-spacing:.15em;text-transform:uppercase;color:var(--accent);font-weight:700}
h1{margin:6px 0 2px;font-size:28px;letter-spacing:-.02em}.sub{color:var(--muted);margin:0}
h2{font-size:17px;margin:28px 0 12px}
section{margin-top:24px}
.verdict{display:flex;gap:22px;align-items:center;background:var(--surface);border:1px solid var(--line);border-left:4px solid var(--lo);border-radius:var(--radius);padding:22px 26px}
.verdict.hi{border-left-color:var(--hi)}.verdict.mid{border-left-color:var(--mid)}
.risk{font-size:46px;font-weight:800;line-height:1;letter-spacing:-.03em}.risk span{font-size:18px;color:var(--muted);font-weight:600}
.verdict.hi .risk{color:var(--hi)}.verdict.mid .risk{color:var(--mid)}.verdict.lo .risk{color:var(--lo)}
.vlabel{font-size:16px;font-weight:700;text-transform:capitalize}.factors{color:var(--muted);font-size:13px;margin-top:2px}
table.grid{width:100%;border-collapse:collapse;background:var(--surface);border:1px solid var(--line);border-radius:10px;overflow:hidden}
th,td{padding:8px 12px;text-align:left;border-bottom:1px solid var(--line);font-size:13.5px;vertical-align:middle}
thead th{background:var(--surface2);font-size:11px;text-transform:uppercase;letter-spacing:.05em;color:var(--muted)}
tbody tr:last-child td{border-bottom:0}.num{text-align:right;font-variant-numeric:tabular-nums}
.file{font-family:ui-monospace,Menlo,Consolas,monospace;font-size:12.5px;overflow-wrap:anywhere}
.score{font-weight:700;font-variant-numeric:tabular-nums}.score.hi{color:var(--hi)}.score.mid{color:var(--mid)}.score.lo{color:var(--lo)}
td.bar{width:130px}td.bar span{display:block;height:8px;border-radius:999px;background:var(--lo)}td.bar span.hi{background:var(--hi)}td.bar span.mid{background:var(--mid)}
.ok{color:var(--lo);font-size:12px;font-weight:600}.gap{color:var(--hi);font-size:12px;font-weight:700}
ul.changed{list-style:none;padding:0;margin:0}ul.changed li{font-family:ui-monospace,monospace;font-size:13px;padding:4px 0;border-bottom:1px solid var(--line)}
footer{margin-top:40px;padding-top:18px;border-top:1px solid var(--line);color:var(--muted);font-size:12.5px}
@media print{:root{--bg:#fff;--surface:#fff;--surface2:#fff;--line:#bbb;--ink:#000}}
`;

function esc(v) {
  if (v === null || v === undefined) return '';
  return String(v).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}
